services:
  redaction-tool:
    build: .
    container_name: redaction-tool
    restart: always
    ports:
      - "9000:8000"
    environment:
      - PORT=8000
      - FLASK_DEBUG=true
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app
      - /app/.venv  # This "anonymous volume" preserves the container's installed packages


