services:
  redaction-tool:
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_DEBUG=1
      - PORT=8000
    command: /app/.venv/bin/gunicorn --bind 0.0.0.0:8000 app:app --reload --workers 1

# Run with docker compose -f docker-compose.yml -f docker-compose.dev.yml up
